name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: aorexe/test-gradle/java/build@main
        with:
          cache: false

  build-maven:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: aorexe/test-gradle/java/build@main
        with:
          cache: false
          set-build-system: 'maven'
