name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-gradle-jar
          path: build/
          retention-days: 1
          overwrite: true

  build-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-maven-jar
          path: target/
